version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: habitflow-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    image: habitflow-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
